name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [ develop ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  buildAndDeploy:
    environment:
      name: github-pages
      url: "https://nduartech.github.io"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Yarn PnP Setup
        uses: Araxeus/setup-yarn-pnp-action@v1
        with:
          node-version: 20
      - name: Build
        run: npm i -g concurrently && yarn && yarn build
        shell: bash
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: 404 Redirect
        run: cp ./packages/host/404.html ./packages/host/dist
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './packages/host/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
